<?php

namespace Database\Seeders;

use App\Models\QuranJuz;
use App\Models\QuranSurah;
use Illuminate\Database\Seeder;

class QuranSurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1, 'Al-Fatihah', 'الفاتحة', 'Pembukaan', 7, 'Makkiyah', 1, 1],
            [2, 'Al-Baqarah', 'البقرة', 'Sapi Betina', 286, 'Madaniyah', 1, 3],
            [3, 'Ali Imran', 'آل عمران', 'Keluarga Imran', 200, 'Madaniyah', 3, 4],
            [4, 'An-Nisa', 'النساء', 'Wanita', 176, 'Madaniyah', 4, 6],
            [5, 'Al-Maidah', 'المائدة', 'Hidangan', 120, 'Madaniyah', 6, 7],
            [6, 'Al-Anam', 'الأنعام', 'Binatang Ternak', 165, 'Makkiyah', 7, 8],
            [7, 'Al-Araf', 'الأعراف', 'Tempat Tertinggi', 206, 'Makkiyah', 8, 9],
            [8, 'Al-Anfal', 'الأنفال', 'Rampasan Perang', 75, 'Madaniyah', 9, 10],
            [9, 'At-Taubah', 'التوبة', 'Pengampunan', 129, 'Madaniyah', 10, 11],
            [10, 'Yunus', 'يونس', 'Nabi Yunus', 109, 'Makkiyah', 11, 11],
            [11, 'Hud', 'هود', 'Nabi Hud', 123, 'Makkiyah', 11, 12],
            [12, 'Yusuf', 'يوسف', 'Nabi Yusuf', 111, 'Makkiyah', 12, 13],
            [13, 'Ar-Rad', 'الرعد', 'Guruh', 43, 'Madaniyah', 13, 13],
            [14, 'Ibrahim', 'ابراهيم', 'Nabi Ibrahim', 52, 'Makkiyah', 13, 13],
            [15, 'Al-Hijr', 'الحجر', 'Gunung Al-Hijr', 99, 'Makkiyah', 14, 14],
            [16, 'An-Nahl', 'النحل', 'Lebah', 128, 'Makkiyah', 14, 14],
            [17, 'Al-Isra', 'الإسراء', 'Perjalanan Malam', 111, 'Makkiyah', 15, 15],
            [18, 'Al-Kahf', 'الكهف', 'Gua', 110, 'Makkiyah', 15, 16],
            [19, 'Maryam', 'مريم', 'Maryam', 98, 'Makkiyah', 16, 16],
            [20, 'Taha', 'طه', 'Taha', 135, 'Makkiyah', 16, 16],
            [21, 'Al-Anbiya', 'الأنبياء', 'Para Nabi', 112, 'Makkiyah', 17, 17],
            [22, 'Al-Hajj', 'الحج', 'Haji', 78, 'Madaniyah', 17, 17],
            [23, 'Al-Muminun', 'المؤمنون', 'Orang-Orang Mukmin', 118, 'Makkiyah', 18, 18],
            [24, 'An-Nur', 'النور', 'Cahaya', 64, 'Madaniyah', 18, 18],
            [25, 'Al-Furqan', 'الفرقان', 'Pembeda', 77, 'Makkiyah', 18, 19],
            [26, 'Asy-Syuara', 'الشعراء', 'Para Penyair', 227, 'Makkiyah', 19, 19],
            [27, 'An-Naml', 'النمل', 'Semut', 93, 'Makkiyah', 19, 20],
            [28, 'Al-Qasas', 'القصص', 'Kisah-Kisah', 88, 'Makkiyah', 20, 20],
            [29, 'Al-Ankabut', 'العنكبut', 'Laba-Laba', 69, 'Makkiyah', 20, 21],
            [30, 'Ar-Rum', 'الروم', 'Bangsa Romawi', 60, 'Makkiyah', 21, 21],
            [31, 'Luqman', 'لقمان', 'Luqman', 34, 'Makkiyah', 21, 21],
            [32, 'As-Sajdah', 'السجدة', 'Sujud', 30, 'Makkiyah', 21, 21],
            [33, 'Al-Ahzab', 'الأحزاب', 'Golongan Yang Bersekutu', 73, 'Madaniyah', 21, 22],
            [34, 'Saba', 'سبإ', 'Kaum Saba', 54, 'Makkiyah', 22, 22],
            [35, 'Fatir', 'فاطer', 'Pencipta', 45, 'Makkiyah', 22, 22],
            [36, 'Yasin', 'يس', 'Yasin', 83, 'Makkiyah', 22, 23],
            [37, 'As-Saffat', 'الصافات', 'Barisan-Barisan', 182, 'Makkiyah', 23, 23],
            [38, 'Sad', 'ص', 'Sad', 88, 'Makkiyah', 23, 23],
            [39, 'Az-Zumar', 'الزمر', 'Rombongan-Rombongan', 75, 'Makkiyah', 23, 24],
            [40, 'Ghafir', 'غافر', 'Yang Mengampuni', 85, 'Makkiyah', 24, 24],
            [41, 'Fussilat', 'فصلت', 'Yang Dijelaskan', 54, 'Makkiyah', 24, 25],
            [42, 'Asy-Syura', 'الشورى', 'Musyawarah', 53, 'Makkiyah', 25, 25],
            [43, 'Az-Zukhruf', 'الزخرف', 'Perhiasan', 89, 'Makkiyah', 25, 25],
            [44, 'Ad-Dukhan', 'الدخان', 'Kabut', 59, 'Makkiyah', 25, 25],
            [45, 'Al-Jasiyah', 'الجاثية', 'Yang Berlutut', 37, 'Makkiyah', 25, 25],
            [46, 'Al-Ahqaf', 'الأحقاف', 'Bukit Pasir', 35, 'Makkiyah', 26, 26],
            [47, 'Muhammad', 'محمد', 'Nabi Muhammad', 38, 'Madaniyah', 26, 26],
            [48, 'Al-Fath', 'الفتح', 'Kemenangan', 29, 'Madaniyah', 26, 26],
            [49, 'Al-Hujurat', 'الحجرات', 'Kamar-Kamar', 18, 'Madaniyah', 26, 26],
            [50, 'Qaf', 'ق', 'Qaf', 45, 'Makkiyah', 26, 26],
            [51, 'Az-Zariyat', 'الذاريات', 'Angin yang Menerbangkan', 60, 'Makkiyah', 26, 27],
            [52, 'At-Tur', 'الطور', 'Bukit Tur', 49, 'Makkiyah', 27, 27],
            [53, 'An-Najm', 'النجم', 'Bintang', 62, 'Makkiyah', 27, 27],
            [54, 'Al-Qamar', 'القمر', 'Bulan', 55, 'Makkiyah', 27, 27],
            [55, 'Ar-Rahman', 'الرحمن', 'Yang Maha Pemurah', 78, 'Madaniyah', 27, 27],
            [56, 'Al-Waqiah', 'الواقعة', 'Hari Kiamat', 96, 'Makkiyah', 27, 27],
            [57, 'Al-Hadid', 'الحديد', 'Besi', 29, 'Madaniyah', 27, 27],
            [58, 'Al-Mujadilah', 'المجادلة', 'Wanita yang Mengajukan Gugatan', 22, 'Madaniyah', 28, 28],
            [59, 'Al-Hasyr', 'الحشر', 'Pengusiran', 24, 'Madaniyah', 28, 28],
            [60, 'Al-Mumtahanah', 'الممتحنة', 'Wanita yang Diuji', 13, 'Madaniyah', 28, 28],
            [61, 'As-Saff', 'الصف', 'Barisan', 14, 'Madaniyah', 28, 28],
            [62, 'Al-Jumuah', 'الجمعة', 'Hari Jumat', 11, 'Madaniyah', 28, 28],
            [63, 'Al-Munafiqun', 'المنافقون', 'Orang-Orang Munafik', 11, 'Madaniyah', 28, 28],
            [64, 'At-Taghabun', 'التغابن', 'Hari Ditampakkan Kesalahan', 18, 'Madaniyah', 28, 28],
            [65, 'At-Talaq', 'الطلاق', 'Talak', 12, 'Madaniyah', 28, 28],
            [66, 'At-Tahrim', 'التحريم', 'Pengharaman', 12, 'Madaniyah', 28, 28],
            [67, 'Al-Mulk', 'الملك', 'Kerajaan', 30, 'Makkiyah', 29, 29],
            [68, 'Al-Qalam', 'القلم', 'Pena', 52, 'Makkiyah', 29, 29],
            [69, 'Al-Haqqah', 'الحاقة', 'Hari Kiamat', 52, 'Makkiyah', 29, 29],
            [70, 'Al-Maarij', 'المعارج', 'Tempat Naik', 44, 'Makkiyah', 29, 29],
            [71, 'Nuh', 'نوح', 'Nabi Nuh', 28, 'Makkiyah', 29, 29],
            [72, 'Al-Jinn', 'الجن', 'Jin', 28, 'Makkiyah', 29, 29],
            [73, 'Al-Muzzammil', 'المزمل', 'Orang yang Berselimut', 20, 'Makkiyah', 29, 29],
            [74, 'Al-Muddassir', 'المدثر', 'Orang yang Berselimut', 56, 'Makkiyah', 29, 29],
            [75, 'Al-Qiyamah', 'القيامة', 'Hari Kiamat', 40, 'Makkiyah', 29, 29],
            [76, 'Al-Insan', 'الانسان', 'Manusia', 31, 'Madaniyah', 29, 29],
            [77, 'Al-Mursalat', 'المرسلات', 'Malaikat-Malaikat yang Diutus', 50, 'Makkiyah', 29, 29],
            [78, 'An-Naba', 'النبإ', 'Berita Besar', 40, 'Makkiyah', 30, 30],
            [79, 'An-Naziat', 'الناzifat', 'Malaikat yang Mencabut', 46, 'Makkiyah', 30, 30],
            [80, 'Abasa', 'عبس', 'Ia Bermuka Masam', 42, 'Makkiyah', 30, 30],
            [81, 'At-Takwir', 'التكوير', 'Menggulung', 29, 'Makkiyah', 30, 30],
            [82, 'Al-Infitar', 'الinfittar', 'Terbelah', 19, 'Makkiyah', 30, 30],
            [83, 'Al-Mutaffifin', 'المطففين', 'Orang-Orang Curang', 36, 'Makkiyah', 30, 30],
            [84, 'Al-Insyiqaq', 'الإنشقاق', 'Terbelah', 25, 'Makkiyah', 30, 30],
            [85, 'Al-Buruj', 'البروج', 'Gugusan Bintang', 22, 'Makkiyah', 30, 30],
            [86, 'At-Tariq', 'الطارق', 'Yang Datang di Malam Hari', 17, 'Makkiyah', 30, 30],
            [87, 'Al-Ala', 'الأعلى', 'Yang Paling Tinggi', 19, 'Makkiyah', 30, 30],
            [88, 'Al-Ghasyiyah', 'الغاشية', 'Hari Pembalasan', 26, 'Makkiyah', 30, 30],
            [89, 'Al-Fajr', 'الفجر', 'Fajar', 30, 'Makkiyah', 30, 30],
            [90, 'Al-Balad', 'البلد', 'Negeri', 20, 'Makkiyah', 30, 30],
            [91, 'Asy-Syams', 'الشمس', 'Matahari', 15, 'Makkiyah', 30, 30],
            [92, 'Al-Lail', 'الليل', 'Malam', 21, 'Makkiyah', 30, 30],
            [93, 'Ad-Duha', 'الضحى', 'Waktu Duha', 11, 'Makkiyah', 30, 30],
            [94, 'Asy-Syarh', 'الشرح', 'Lapang', 8, 'Makkiyah', 30, 30],
            [95, 'At-Tin', 'التين', 'Buah Tin', 8, 'Makkiyah', 30, 30],
            [96, 'Al-Alaq', 'العلق', 'Segumpal Darah', 19, 'Makkiyah', 30, 30],
            [97, 'Al-Qadr', 'القدر', 'Kemuliaan', 5, 'Makkiyah', 30, 30],
            [98, 'Al-Bayyinah', 'البينة', 'Bukti Nyata', 8, 'Madaniyah', 30, 30],
            [99, 'Az-Zalzalah', 'الزلزلة', 'Guncangan', 8, 'Madaniyah', 30, 30],
            [100, 'Al-Adiyat', 'العاديات', 'Kuda yang Berlari Kencang', 11, 'Makkiyah', 30, 30],
            [101, 'Al-Qariah', 'القارعة', 'Hari Kiamat', 11, 'Makkiyah', 30, 30],
            [102, 'At-Takatsur', 'التكاثر', 'Bermegah-Megahan', 8, 'Makkiyah', 30, 30],
            [103, 'Al-Asr', 'العصر', 'Masa', 3, 'Makkiyah', 30, 30],
            [104, 'Al-Humazah', 'الهمزة', 'Pengumpat', 9, 'Makkiyah', 30, 30],
            [105, 'Al-Fil', 'الفيل', 'Gajah', 5, 'Makkiyah', 30, 30],
            [106, 'Quraisy', 'قريش', 'Suku Quraisy', 4, 'Makkiyah', 30, 30],
            [107, 'Al-Maun', 'الماعون', 'Barang Berguna', 7, 'Makkiyah', 30, 30],
            [108, 'Al-Kausar', 'الكوثر', 'Nikmat yang Banyak', 3, 'Makkiyah', 30, 30],
            [109, 'Al-Kafirun', 'الكافرون', 'Orang-Orang Kafir', 6, 'Makkiyah', 30, 30],
            [110, 'An-Nasr', 'النصر', 'Pertolongan', 3, 'Madaniyah', 30, 30],
            [111, 'Al-Lahab', 'اللهب', 'Gejolak Api', 5, 'Makkiyah', 30, 30],
            [112, 'Al-Ikhlas', 'الإخلاص', 'Ikhlas', 4, 'Makkiyah', 30, 30],
            [113, 'Al-Falaq', 'الفلق', 'Subuh', 5, 'Makkiyah', 30, 30],
            [114, 'An-Nas', 'الناس', 'Manusia', 6, 'Makkiyah', 30, 30],
        ];

        foreach ($surahs as [$number, $latin, $arabic, $meaning, $totalAyah, $place, $startJuz, $endJuz]) {
            QuranSurah::query()->updateOrCreate(
                ['number' => $number],
                [
                    'name_latin' => $latin,
                    'name_arabic' => $arabic,
                    'meaning' => $meaning,
                    'total_ayah' => $totalAyah,
                    'revelation_place' => $place,
                    'start_juz_id' => QuranJuz::query()->where('number', $startJuz)->value('id'),
                    'end_juz_id' => QuranJuz::query()->where('number', $endJuz)->value('id'),
                ]
            );
        }
    }
}
